# Nom du playbook : Création d'utilisateurs LDAP
# Auteur : Noah Berclaz
# Date : 25.04.2025
# Description : Ce playbook Crée de nouveaux utilisateurs LDAP

---
users:
  - username: "cfit"
    full_name: "Carlos Fitipaldi"
    password: "Parker75"
    roles:
      - user
      - ldapadmin
      - sudoadmin