---
- name: Modifier les utilisateurs existants
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    append: yes
    state: present
  loop: "{{ users }}"
  register: user_modify_results
  ignore_errors: true

- name: Mettre à jour la clé SSH si définie
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  when: item.ssh_key is defined
  loop: "{{ users }}"
  register: ssh_key_results
  ignore_errors: true

- name: Journaliser les erreurs de modification utilisateur
  ansible.builtin.shell: |
    echo "[{{ ansible_date_time.iso8601 }}] ERREUR modification de {{ item.item.name }} sur {{ inventory_hostname }} : {{ item.msg }}" \
    >> {{ log_file }}
  when: item.failed
  loop: "{{ user_modify_results.results }}"
  delegate_to: localhost
  run_once: false

- name: Journaliser les erreurs de mise à jour de clé SSH
  ansible.builtin.shell: |
    echo "[{{ ansible_date_time.iso8601 }}] ERREUR clé SSH de {{ item.item.name }} sur {{ inventory_hostname }} : {{ item.msg }}" \
    >> {{ log_file }}
  when: item.failed
  loop: "{{ ssh_key_results.results }}"
  delegate_to: localhost
  run_once: false