---
- name: Installer les paquets client LDAP
  apt:
    name:
      - libnss-ldapd
      - libpam-ldapd
      - nslcd
      - ldap-utils
    state: present
    update_cache: yes

- name: Configurer nslcd.conf
  template:
    src: nslcd.conf.j2
    dest: /etc/nslcd.conf
    mode: '0600'

- name: Configurer nsswitch
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^({{ item }})\s+.*'
    line: '{{ item }}: files ldap'
    backrefs: yes
  loop:
    - passwd
    - group
    - shadow

- name: Activer pam_mkhomedir
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: 'session required pam_unix.so'
    line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0022'

- name: Redémarrer les services LDAP
  service:
    name: nslcd
    state: restarted