# Nom du playbook : Création d'utilisateurs LDAP
# Auteur : Noah Berclaz
# Date : 25.04.2025
# Description : Ce playbook Crée de nouveaux utilisateurs LDAP

---
- name: Créer les utilisateurs LDAP
  community.general.ldap_entry:
    dn: "uid={{ item.username }},{{ base_dn }}"
    server_uri: "{{ ldap_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    attributes:
      cn: "{{ item.full_name }}"
      sn: "{{ item.full_name.split(' ')[-1] }}"
      uid: "{{ item.username }}"
      uidNumber: "{{ item.uidNumber }}"
      homeDirectory: "/home/{{ item.username }}"
      loginShell: "/bin/bash"
      userPassword: "{{ item.password | password_hash('sha512') }}"
  loop: "{{ users }}"
  become: true

# 2. Activer pam_mkhomedir pour auto-création des homes
- name: Activer pam_mkhomedir dans common-session
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: 'session\s+required\s+pam_unix.so'
    line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0022'
  become: yes

- name: Activer pam_mkhomedir dans sshd
  lineinfile:
    path: /etc/pam.d/sshd
    insertafter: 'session\s+required\s+pam_unix.so'
    line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0022'
  become: yes