# Nom du playbook : Création d'un client LDAP : handler
# Auteur : Noah Berclaz
# Date : 28.04.2025
# Description : Ce handler redémarre le service ldap une fois configuré

---
- name: Restart nslcd
  service:
    name: nslcd
    state: restarted

- name: Redémarrer les services LDAP
  service:
    name: nslcd
    state: restarted

- name: Restart sshd
  service:
    name: ssh
    state: restarted
  become: true