# Nom du playbook : Création d'utilisateurs LDAP
# Auteur : Noah Berclaz
# Date : 25.04.2025
# Description : Ce playbook Crée de nouveaux utilisateurs LDAP

---
- name: Créer des utilisateurs sur le serveur
  hosts: ldapserver
  vars_files:
    - ../secrets/secrets.yml
  become: yes

  roles:
    - ../roles/openldap_newuser