---
- name: Installer les paquets nécessaires pour client LDAP
  apt:
    name:
      - libnss-ldapd
      - libpam-ldapd
      - ldap-utils
    state: present
    update_cache: yes

- name: Configurer /etc/nslcd.conf
  copy:
    dest: /etc/nslcd.conf
    content: |
      uid nslcd
      gid nslcd
      uri {{ ldap_uri }}
      base {{ ldap_base }}
      ssl on
      tls_reqcert allow

- name: Configurer nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^({{ item.key }})\s+.*'
    line: '{{ item.key }}: files ldap'
    backrefs: yes
  loop:
    - { key: 'passwd' }
    - { key: 'group' }
    - { key: 'shadow' }

- name: Installer sudo-ldap
  ansible.builtin.apt:
    name: sudo-ldap
    state: present

- name: Configurer sudo via LDAP
  ansible.builtin.template:
    src: sudo-ldap.conf.j2
    dest: /etc/sudo-ldap.conf
    mode: '0644'

- name: Activer la création automatique des home directories
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: '^# and here are more per-package modules'
    line: 'session required        pam_mkhomedir.so skel=/etc/skel/ umask=0022'

- name: Redémarrer les services LDAP client
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nslcd
    - ssh
