# Nom du playbook : Création d'un client LDAP
# Auteur : Noah Berclaz
# Date : 28.04.2025
# Description : Ce playbook Crée de nouvelles machines clientes LDAP

---
- name: Configurer le service OpenLDAP sur un serveur client
  hosts: ldapclient
  vars_files:
    - ../secrets/secrets.yml
  become: yes
  roles:
    - linux_server
    - openldap_newclient