# Nom du playbook : Création d'un client LDAP : vars files
# Auteur : Noah Berclaz
# Date : 28.04.2025
# Description : Ce playbook Crée de nouvelles machines clientes LDAP

---
ldap_server_ip: "172.20.10.3"       # Adresse IP ou FQDN du serveur LDAP
ldap_base_dn: "dc=yoga,dc=ch"  # Base DN (modifie selon ton domaine LDAP)