---
- name: Créer les OU
  community.general.ldap_entry:
    dn: "ou=users,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}"
    objectClass: [organizationalUnit]
    attributes:
      ou: users
    bind_dn: "cn=admin,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}"
    bind_pw: "{{ ldap_admin_password }}"
    server_uri: "ldap://{{ inventory_hostname }}"
    validate_certs: false

- name: Créer les groupes LDAP
  community.general.ldap_entry:
    dn: "cn={{ item }},ou=users,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}"
    objectClass: [posixGroup]
    attributes:
      cn: "{{ item }}"
      gidNumber: "{{ 10000 + loop.index }}"
    bind_dn: "cn=admin,dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}"
    bind_pw: "{{ ldap_admin_password }}"
    server_uri: "ldap://{{ inventory_hostname }}"
    validate_certs: false
  loop:
    - sudoadmin
    - ldapadmin
    - user

- name: Autoriser sudoadmin dans sudoers
  copy:
    dest: /etc/sudoers.d/sudoadmin
    content: "%sudoadmin ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'